//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logintab
    {
        public int LoginId { get; set; }
        public int RegId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string LogType { get; set; }
    }
}
