//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPROJECT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MVCPOJECTEntities : DbContext
    {
        public MVCPOJECTEntities()
            : base("name=MVCPOJECTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applicationtab> Applicationtabs { get; set; }
        public virtual DbSet<Companytab> Companytabs { get; set; }
        public virtual DbSet<Jobtab1> Jobtab1 { get; set; }
        public virtual DbSet<Logintab> Logintabs { get; set; }
        public virtual DbSet<Usertab> Usertabs { get; set; }
    
        public virtual int sp_addjob(Nullable<int> companyid, string jobtitle, string jobdescription, string location, Nullable<decimal> experience, string skills, string qualification, Nullable<System.DateTime> currentdate, Nullable<System.DateTime> enddate, string jobstatus)
        {
            var companyidParameter = companyid.HasValue ?
                new ObjectParameter("companyid", companyid) :
                new ObjectParameter("companyid", typeof(int));
    
            var jobtitleParameter = jobtitle != null ?
                new ObjectParameter("jobtitle", jobtitle) :
                new ObjectParameter("jobtitle", typeof(string));
    
            var jobdescriptionParameter = jobdescription != null ?
                new ObjectParameter("jobdescription", jobdescription) :
                new ObjectParameter("jobdescription", typeof(string));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var experienceParameter = experience.HasValue ?
                new ObjectParameter("Experience", experience) :
                new ObjectParameter("Experience", typeof(decimal));
    
            var skillsParameter = skills != null ?
                new ObjectParameter("skills", skills) :
                new ObjectParameter("skills", typeof(string));
    
            var qualificationParameter = qualification != null ?
                new ObjectParameter("Qualification", qualification) :
                new ObjectParameter("Qualification", typeof(string));
    
            var currentdateParameter = currentdate.HasValue ?
                new ObjectParameter("currentdate", currentdate) :
                new ObjectParameter("currentdate", typeof(System.DateTime));
    
            var enddateParameter = enddate.HasValue ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(System.DateTime));
    
            var jobstatusParameter = jobstatus != null ?
                new ObjectParameter("Jobstatus", jobstatus) :
                new ObjectParameter("Jobstatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_addjob", companyidParameter, jobtitleParameter, jobdescriptionParameter, locationParameter, experienceParameter, skillsParameter, qualificationParameter, currentdateParameter, enddateParameter, jobstatusParameter);
        }
    
        public virtual int sp_companyreg(string companyname, string phone, string email, string address)
        {
            var companynameParameter = companyname != null ?
                new ObjectParameter("companyname", companyname) :
                new ObjectParameter("companyname", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_companyreg", companynameParameter, phoneParameter, emailParameter, addressParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_IsApplied(Nullable<int> userId, Nullable<int> jobId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var jobIdParameter = jobId.HasValue ?
                new ObjectParameter("JobId", jobId) :
                new ObjectParameter("JobId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_IsApplied", userIdParameter, jobIdParameter);
        }
    
        public virtual int sp_Jobsearch(string qry)
        {
            var qryParameter = qry != null ?
                new ObjectParameter("qry", qry) :
                new ObjectParameter("qry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Jobsearch", qryParameter);
        }
    
        public virtual ObjectResult<sp_jobview_Result> sp_jobview(Nullable<int> jobId, Nullable<int> companyId)
        {
            var jobIdParameter = jobId.HasValue ?
                new ObjectParameter("JobId", jobId) :
                new ObjectParameter("JobId", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_jobview_Result>("sp_jobview", jobIdParameter, companyIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_logincountid(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_logincountid", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_loginid(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_loginid", usernameParameter, passwordParameter);
        }
    
        public virtual int sp_LoginInsert(Nullable<int> regid, string username, string password, string logType)
        {
            var regidParameter = regid.HasValue ?
                new ObjectParameter("Regid", regid) :
                new ObjectParameter("Regid", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var logTypeParameter = logType != null ?
                new ObjectParameter("LogType", logType) :
                new ObjectParameter("LogType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LoginInsert", regidParameter, usernameParameter, passwordParameter, logTypeParameter);
        }
    
        public virtual ObjectResult<string> sp_logintype(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_logintype", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_maxloginid(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_maxloginid", usernameParameter, passwordParameter);
        }
    
        public virtual int sp_PostApplication(Nullable<int> userId, Nullable<int> jobId, Nullable<System.DateTime> applicationDate, string resume, string status)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var jobIdParameter = jobId.HasValue ?
                new ObjectParameter("JobId", jobId) :
                new ObjectParameter("JobId", typeof(int));
    
            var applicationDateParameter = applicationDate.HasValue ?
                new ObjectParameter("ApplicationDate", applicationDate) :
                new ObjectParameter("ApplicationDate", typeof(System.DateTime));
    
            var resumeParameter = resume != null ?
                new ObjectParameter("Resume", resume) :
                new ObjectParameter("Resume", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PostApplication", userIdParameter, jobIdParameter, applicationDateParameter, resumeParameter, statusParameter);
        }
    
        public virtual ObjectResult<sp_SelectAll_Result> sp_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SelectAll_Result>("sp_SelectAll");
        }
    
        public virtual int sp_userreg(string name, string gender, string email, string phone, Nullable<int> age, string address, string qualification, Nullable<decimal> experienceyears, string skills, string status)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var qualificationParameter = qualification != null ?
                new ObjectParameter("qualification", qualification) :
                new ObjectParameter("qualification", typeof(string));
    
            var experienceyearsParameter = experienceyears.HasValue ?
                new ObjectParameter("Experienceyears", experienceyears) :
                new ObjectParameter("Experienceyears", typeof(decimal));
    
            var skillsParameter = skills != null ?
                new ObjectParameter("skills", skills) :
                new ObjectParameter("skills", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_userreg", nameParameter, genderParameter, emailParameter, phoneParameter, ageParameter, addressParameter, qualificationParameter, experienceyearsParameter, skillsParameter, statusParameter);
        }
    }
}
